# Environment variables
# Create a copy of this file and rename it to `.env`

# Basic
APP_ENV="DEV"
APP_SETTINGS_LOG_DIR="/tmp/"
APP_SETTINGS_FRONTEND_URL="http://localhost:3000/"

# MongoDB
APP_SETTINGS_MONGO__HOST="xxxxxxxxxxxxx"
APP_SETTINGS_MONGO__DB="xxxxxxxxxxx"
APP_SETTINGS_MONGO__USERNAME="xxxxxxxxxxxxx"
APP_SETTINGS_MONGO__PASSWORD="xxxxxxxxxxxxxxxx"

# AWS
APP_SETTINGS_AWS_ENDPOINT="https://s3:/"
APP_SETTINGS_AWS_ACCESS_KEY_ID ="XXXXXXXXXX"
APP_SETTINGS_AWS_ACCESS_KEY_SECRET="XXXXXXXXXXX"
APP_SETTINGS_AWS_REGION="XXXXXXXXXXXXXXXXXX"
APP_SETTINGS_AWS_S3_BUCKET="XXXXXXXXXXXXXXXXXXXX"
APP_SETTINGS_AWS_USE_SSL="XXXXXXXXXXXXXXXXX"

# IP infos
APP_SETTINGS_IP_INFO_URL="https://ipinfo.io/"
